# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: '1.0.4'

# Site settings
title:              'Zan Baldwin'
logo:               # Logo image URL
description:        'Software Developer'
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://zanbaldwin.com' # The base hostname & protocol for your site
twitter:            'https://twitter.com/ZanBaldwin'

markdown:  'kramdown'
permalink: 'pretty'
paginate:  11
sass:
    style: 'compressed'

plugins:
    - 'jekyll-paginate'
    - 'jekyll/tagging'
    - 'jekyll-feed'
    - 'jekyll-sitemap'
    - 'jekyll-seo-tag'

include:
    - '_pages'

exclude:
    - 'vendor'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Makefile'

# Tags
tag_page_dir:         'tag'
tag_page_layout:      'tag_page'
tag_permalink_style:  'pretty'

# Pages path
defaults:
    - scope:
          path: '_pages'
      values:
          permalink: '/:basename:output_ext'

# Authors
authors:
    zanbaldwin:
        name:     'Zan Baldwin'
        bio:      'Symfony Software Developer'
        gravatar: 'https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150'
        email:    'hello@zanbaldwin.com'
        website:  'https://zanbaldwin.com'
        github:   'https://github.com/zanbaldwin'
        twitter:  'https://twitter.com/ZanBaldwin'
